CREATE TABLE IF NOT EXISTS votes (id TEXT PRIMARY KEY, egg INTEGER NOT NULL DEFAULT 0, flower INTEGER NOT NULL DEFAULT 0, banana INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS hits (key TEXT PRIMARY KEY, n INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS feedback (id INTEGER PRIMARY KEY AUTOINCREMENT, text TEXT NOT NULL, page TEXT, ts TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS perm_reports (id INTEGER PRIMARY KEY AUTOINCREMENT, company TEXT NOT NULL, tier TEXT NOT NULL, note TEXT NOT NULL, link TEXT, ts TEXT NOT NULL);
