name = "liuziqingbao-votes"
main = "index.js"
compatibility_date = "2026-09-01"

[vars]
ORIGIN = "https://tomyang1993.github.io"

[[d1_databases]]
binding = "DB"
database_name = "liuziqingbao"
database_id = "31c48bd5-e98f-46f6-b314-69dd9763287a"
